### ISSUE TITLE
mainブランチの保護設定をしてください

### ISSUE THREAD

**Issue by taishi-matsumura** [human-osaka-game-2020/nakano_repository#5]
PRでのコードレビューをpassしないとmainブランチにmergeできないように設定しておいた方が良いかと思います。
対応しないのであれば、本Issueに「won't fix(修正予定無し)」のラベルを貼り、その旨を返信した上でcloseしておいてください。
「Close with comment」のボタンを押せばメッセージ投稿とIssueのcloseをセットでできます。

**Comment by yuki-nakano** [comment]
mainブランチへのマージをプルリクでの承認なしでできないように設定しました。

**Comment by taishi-matsumura** [comment]
設定されていることが確認できたのでcloseします。

工程が増えるので時間は掛かりますが、頑張って進めていきましょう！💪
